name: BeyondCTAProject
options:
    bundleIdPrefix: beyondCta.project
targets:
  BeyondCTAProject:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: BeyondCTAProject
    schemes:
        BeyondCTAProject:
        testTargetName: BeyondCTAProjectTests
    preBuildScripts:
      - path: ./Scripts/before-compile.sh
        name: before-compile
        shell: "/bin/bash"

  BeyondCTAProjectTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    sources: BeyondCTAProjectTests
    dependencies:
      - target: BeyondCTAProject
    settings:
      INFOPLIST_FILE: BeyondCTAProject/Info.plist
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @loader_path/Frameworks"
      LD_RUNPATH_SEARCH_PATHS[sdk=macosx*]: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks"

  # BeyondCTAProjectUITests:
  #   type: bundle.ui-testing
  #   platform: iOS
  #   deploymentTarget: "13.0"
  #   sources: BeyondCTAProjectUITests
  #   dependencies:
  #     - target: BeyondCTAProject
